apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kh1k
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kh1k
    app.kubernetes.io/part-of: hacbs-test-project-1
  name: hacbs-test-project-kh1kbtxw
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hacbs-test-project-kh1k
    weight: 100
status: {}
