apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kh1k
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kh1k
    app.kubernetes.io/part-of: hacbs-test-project-1
  name: hacbs-test-project-kh1k
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: hacbs-test-project-kh1k
status:
  loadBalancer: {}
